# Generated by Django 3.0.3 on 2020-02-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemetadata", name="location", field=models.URLField(),
        ),
    ]
