# Generated by Django 3.0.3 on 2020-03-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_auto_20200226_1726"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemetadata",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
