# Generated by Django 3.0.3 on 2020-03-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_filemetadata_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemetadata',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
